within SMArtInt.Blocks;
model EvaluateRecurrentNeuralNet
  extends BaseClasses.BaseRecurrentNeuralNet(runInterferenceHistory(flatteningMethod=SMArtInt.Internal.Types.RNNFlatteningMethod.OldFIrstInputSeq));
  Modelica.Blocks.Interfaces.RealInput u[batchSize,numberOfInputs] annotation (Placement(transformation(extent={{-140,-20},{-100,20}}), iconTransformation(extent={{-140,-20},{-100,20}})));
  Modelica.Blocks.Interfaces.RealOutput y[batchSize,numberOfOutputs] annotation (Placement(transformation(extent={{100,-10},{120,10}}), iconTransformation(extent={{100,-10},{120,10}})));
  Modelica.Blocks.Interfaces.RealOutput ySequences[batchSize,numberOfOutputs,nHistoricElements] if returnSequences annotation (Placement(transformation(extent={{100,-60},{120,-40}}), iconTransformation(extent={{100,-60},{120,-40}})));

equation
  connect(u, runInterferenceHistory.u) annotation (Line(points={{-120,0},{-10,0}}, color={0,0,127}));
  connect(runInterferenceHistory.y, y) annotation (Line(points={{11,0},{110,0}}, color={0,0,127}));
  connect(runInterferenceHistory.ySequences, ySequences) annotation (Line(points={{10,-6},{40,-6},{40,-50},{110,-50}}, color={0,0,127}));
  annotation (Documentation(info="<html>
<p>Use this block if you want to include a recurrent neural network in Modelica.</p>
<p>Please place this block in your model and</p>
<ul>
<li>give the path to the TFLite/ONNX model</li>
<li>specify the number of inputs</li>
<li>specify the sampling interval and how many elements from previous times should be fed into the net</li>
<li>provide the values for the input of the block and use the outputs in the same manner as it was done during training</li>
</ul>
<p>In continuous mode the historic values are generated by a delay. You could choose between the computational improved Clara-Delay and the delay in the Modelica-Standard-Library. If continuous is deactivated the model will create an event when reaching the sampling time - this should be avoided for performance reasons.</p>
<p>As tensorflow lite uses a flattened input array, you have to specify the flattening method. In the standard tensorflow setting you have to use the predefined option OldFirstInputSequential.</p>
<p>The example <a href=\"modelica://SMArtInt.Tester.ExamplePI.TFLite.TF_PI_RNN_tflite\">TF_PI_RNN_tflite</a> uses this block.</p>

<h4>TensorFlow Lite FlexOps</h4>

<p>
To use FlexOps with the TensorFlow Lite runtime, additional dynamic libraries must be provided in the SMArtInt library resources. Follow the steps below:
</p>

<ol>
  <li>
    Copy the appropriate FlexOps library into the corresponding platform folder
    (<code>win64</code> or <code>linux64</code>) inside the
    <a href=\"modelica://SMArtInt/Resources/Library/\">Resources Library folder</a>:
    <ul>
      <li><b>Windows:</b> <code>tensorflowlite_flex.dll</code></li>
      <li><b>Linux:</b> <code>libtensorflowlite_flex.so</code></li>
    </ul>
  </li>
  <li>
    Activate TensorFlow Lite FlexOps usage in the model parameter dialog.
  </li>
</ol>

<h4>CUDA GPU Support for ONNX Runtime</h4>

<p>
To use ONNX Runtime with GPU acceleration, CUDA must be installed on the operating system
(tested with CUDA version 13.0), and a CUDA-compatible GPU must be available.
In addition, the required ONNX Runtime GPU provider libraries must be provided in the SMArtInt library resources.
Follow the steps below:
</p>

<ol>
  <li>
    Download the ONNX Runtime build with GPU support from:
    <br>
    <a href=\"https://github.com/microsoft/onnxruntime/releases/tag/v1.23.2\">
      ONNX Runtime v1.23.2 Release
    </a>
  </li>

  <li>
    Select and extract the appropriate package for your operating system:
    <ul>
      <li><b>Windows:</b> <code>onnxruntime-win-x64-gpu-1.23.2.zip</code></li>
      <li><b>Linux:</b> <code>onnxruntime-linux-x64-gpu-1.23.2.tgz</code></li>
    </ul>
  </li>

  <li>
    Copy the required provider libraries into the corresponding platform folder
    (<code>win64</code> or <code>linux64</code>) inside the
    <a href=\"modelica://SMArtInt/Resources/Library/\">Resources Library folder</a>:
    <ul>
      <li><code>onnxruntime_providers_cuda.dll</code> / <code>.so</code></li>
      <li><code>onnxruntime_providers_shared.dll</code> / <code>.so</code></li>
    </ul>
  </li>

  <li>
    Activate GPU usage in the model parameter dialog.
  </li>
</ol>

</html>"));
end EvaluateRecurrentNeuralNet;
