within SMArtInt.Blocks;
model EvaluateRecurrentNeuralNet
  extends BaseClasses.BaseRecurrentNeuralNet(runInterferenceHistory(flatteningMethod=SMArtInt.Internal.Types.RNNFlatteningMethod.OldFIrstInputSeq));
  Modelica.Blocks.Interfaces.RealInput u[batchSize,numberOfInputs] annotation (Placement(transformation(extent={{-110,-10},{-90,10}}), iconTransformation(extent={{-110,-10},{-90,10}})));
  Modelica.Blocks.Interfaces.RealOutput y[batchSize,numberOfOutputs] annotation (Placement(transformation(extent={{90,-10},{110,10}}), iconTransformation(extent={{90,-10},{110,10}})));
  Modelica.Blocks.Interfaces.RealOutput ySequences[batchSize,numberOfOutputs,nHistoricElements] if returnSequences annotation (Placement(transformation(extent={{90,-60},{110,-40}}), iconTransformation(extent={{90,-60},{110,-40}})));

equation
  connect(u, runInterferenceHistory.u) annotation (Line(points={{-100,0},{-10,0}}, color={0,0,127}));
  connect(runInterferenceHistory.y, y) annotation (Line(points={{9.8,0},{100,0}}, color={0,0,127}));
  connect(runInterferenceHistory.ySequences, ySequences) annotation (Line(points={{10,-6},{40,-6},{40,-50},{100,-50}}, color={0,0,127}));
  annotation (Documentation(info="<html>
<p>Use this block if you want to include a recurrent neural network in Modelica.</p>
<p>Please place this block in your model and</p>
<ul>
<li>give the path to the TFLite/ONNX model</li>
<li>specify the number of inputs</li>
<li>specify the sampling interval and how many elements from previous times should be fed into the net</li>
<li>provide the values for the input of the block and use the outputs in the same manner as it was done during training</li>
</ul>
<p>In continuous mode the historic values are generated by a delay. You could choose between the computational improved Clara-Delay and the delay in the Modelica-Standard-Library. If continuous is deactivated the model will create an event when reaching the sampling time - this should be avoided for performance reasons.</p>
<p>As tensorflow lite uses a flattened input array, you have to specify the flattening method. In the standard tensorflow setting you have to use the predefined option OldFirstInputSequential.</p>
<p>The example <a href=\"modelica://SMArtInt.Tester.ExamplePI.TFLite.TF_PI_RNN_tflite\">TF_PI_RNN_tflite</a> uses this block.</p>
</html>"));
end EvaluateRecurrentNeuralNet;
